/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import main.Main;

/**
 *
 * @author kevin.guimaraes
 */
public class CadastrarDisciplinaSecretaria extends javax.swing.JFrame {

    private Main  oMain ; 
    
    /**
     * Creates new form TelaCadastrarCursoSecretaria
     */
    public CadastrarDisciplinaSecretaria(Main oMain) {
        initComponents();
        this.oMain = oMain; 
    }
    public CadastrarDisciplinaSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1_Dias = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1_PainelMaior = new javax.swing.JPanel();
        jPanel2_PainelMenor = new javax.swing.JPanel();
        jLabel2_Ano = new javax.swing.JLabel();
        jLabel3_Semestre = new javax.swing.JLabel();
        jLabel4_Dias = new javax.swing.JLabel();
        jLabel5_Horarios = new javax.swing.JLabel();
        jTextField1_Ano = new javax.swing.JTextField();
        jTextField2_Semestre = new javax.swing.JTextField();
        jRadioButton1_Segunda = new javax.swing.JRadioButton();
        jRadioButton2_Terça = new javax.swing.JRadioButton();
        jRadioButton3_Quarta = new javax.swing.JRadioButton();
        jRadioButton4_Quinta = new javax.swing.JRadioButton();
        jRadioButton5_Sexta = new javax.swing.JRadioButton();
        jTextField3_HorarioComeco1 = new javax.swing.JTextField();
        jTextField4_HorarioComeco2 = new javax.swing.JTextField();
        jTextField5_HorarioTermino1 = new javax.swing.JTextField();
        jTextField6_HorarioTermino2 = new javax.swing.JTextField();
        jButton1_Salvar = new javax.swing.JButton();
        jLabel1_ID = new javax.swing.JLabel();
        jTextField1_ID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1_Alterar = new javax.swing.JButton();
        jButton2_Sair = new javax.swing.JButton();
        jLabel1_Titulo = new javax.swing.JLabel();
        jLabel1_Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 550));
        setSize(new java.awt.Dimension(701, 550));
        getContentPane().setLayout(null);

        jPanel1_PainelMaior.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2_PainelMenor.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2_PainelMenor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2_Ano.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2_Ano.setText("Ano:");

        jLabel3_Semestre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3_Semestre.setText("Semestre: ");

        jLabel4_Dias.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4_Dias.setText("Dias da Semana: ");

        jLabel5_Horarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5_Horarios.setText("Horários de Realização: ");

        jRadioButton1_Segunda.setText("Segunda-Feira");

        jRadioButton2_Terça.setText("Terça-Feira");

        jRadioButton3_Quarta.setText("Quarta-Feira");

        jRadioButton4_Quinta.setText("Quinta-Feira");

        jRadioButton5_Sexta.setText("Sexta-Feira");

        jButton1_Salvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1_Salvar.setText("Salvar");

        jLabel1_ID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1_ID.setText("ID: ");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Status: ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton1.setText("Ativo");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton2.setText("Inativo");

        jButton1_Alterar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1_Alterar.setText("Alterar");

        javax.swing.GroupLayout jPanel2_PainelMenorLayout = new javax.swing.GroupLayout(jPanel2_PainelMenor);
        jPanel2_PainelMenor.setLayout(jPanel2_PainelMenorLayout);
        jPanel2_PainelMenorLayout.setHorizontalGroup(
            jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton2))
                        .addComponent(jLabel4_Dias)
                        .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                            .addComponent(jRadioButton4_Quinta)
                            .addGap(10, 10, 10)
                            .addComponent(jRadioButton5_Sexta))
                        .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                                .addComponent(jTextField4_HorarioComeco2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField6_HorarioTermino2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                                .addComponent(jLabel5_Horarios)
                                .addGap(4, 4, 4)
                                .addComponent(jTextField3_HorarioComeco1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5_HorarioTermino1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                                .addComponent(jLabel2_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jTextField1_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                                .addComponent(jLabel3_Semestre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2_Semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                            .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                                    .addComponent(jRadioButton1_Segunda)
                                    .addGap(0, 0, 0)
                                    .addComponent(jRadioButton2_Terça))
                                .addComponent(jLabel1))
                            .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                                    .addComponent(jLabel1_ID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jRadioButton3_Quarta))))
                    .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton1_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        jPanel2_PainelMenorLayout.setVerticalGroup(
            jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_ID)
                    .addComponent(jTextField1_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_Ano)
                    .addComponent(jTextField1_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2_Semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3_Semestre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4_Dias)
                .addGap(7, 7, 7)
                .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1_Segunda, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2_Terça, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3_Quarta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4_Quinta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton5_Sexta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2_PainelMenorLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5_Horarios))
                    .addComponent(jTextField3_HorarioComeco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5_HorarioTermino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4_HorarioComeco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6_HorarioTermino2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2_PainelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Salvar)
                    .addComponent(jButton1_Alterar))
                .addGap(24, 24, 24))
        );

        jButton2_Sair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2_Sair.setText("Sair");
        jButton2_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_SairActionPerformed(evt);
            }
        });

        jLabel1_Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1_Titulo.setText("Cadastro de Disciplinas");

        jLabel1_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apresentacao/graduation-hat-and-diploma-2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1_PainelMaiorLayout = new javax.swing.GroupLayout(jPanel1_PainelMaior);
        jPanel1_PainelMaior.setLayout(jPanel1_PainelMaiorLayout);
        jPanel1_PainelMaiorLayout.setHorizontalGroup(
            jPanel1_PainelMaiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_PainelMaiorLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1_PainelMaiorLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel2_PainelMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1_PainelMaiorLayout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(jButton2_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1_PainelMaiorLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1_Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1_PainelMaiorLayout.setVerticalGroup(
            jPanel1_PainelMaiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1_PainelMaiorLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel2_PainelMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1_PainelMaiorLayout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(jButton2_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1_Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1_PainelMaior);
        jPanel1_PainelMaior.setBounds(0, 0, 690, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_SairActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButton2_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplinaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplinaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplinaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplinaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarDisciplinaSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup1_Dias;
    private javax.swing.JButton jButton1_Alterar;
    private javax.swing.JButton jButton1_Salvar;
    private javax.swing.JButton jButton2_Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Fundo;
    private javax.swing.JLabel jLabel1_ID;
    private javax.swing.JLabel jLabel1_Titulo;
    private javax.swing.JLabel jLabel2_Ano;
    private javax.swing.JLabel jLabel3_Semestre;
    private javax.swing.JLabel jLabel4_Dias;
    private javax.swing.JLabel jLabel5_Horarios;
    private javax.swing.JPanel jPanel1_PainelMaior;
    private javax.swing.JPanel jPanel2_PainelMenor;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton1_Segunda;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton2_Terça;
    private javax.swing.JRadioButton jRadioButton3_Quarta;
    private javax.swing.JRadioButton jRadioButton4_Quinta;
    private javax.swing.JRadioButton jRadioButton5_Sexta;
    private javax.swing.JTextField jTextField1_Ano;
    private javax.swing.JTextField jTextField1_ID;
    private javax.swing.JTextField jTextField2_Semestre;
    private javax.swing.JTextField jTextField3_HorarioComeco1;
    private javax.swing.JTextField jTextField4_HorarioComeco2;
    private javax.swing.JTextField jTextField5_HorarioTermino1;
    private javax.swing.JTextField jTextField6_HorarioTermino2;
    // End of variables declaration//GEN-END:variables
}
