/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import main.Main;

/**
 *
 * @author kevin.guimaraes
 */
public class CadastrarDisciplinaSecretaria extends javax.swing.JFrame {

    private Main  oMain ; 
    
    /**
     * Creates new form TelaCadastrarCursoSecretaria
     */
    public CadastrarDisciplinaSecretaria(Main oMain) {
        initComponents();
        this.oMain = oMain; 
    }
    public CadastrarDisciplinaSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1_Dias = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1_PainelMaior = new javax.swing.JPanel();
        jPanel2_PainelMenor = new javax.swing.JPanel();
        jLabel2_Ano = new javax.swing.JLabel();
        jLabel3_Semestre = new javax.swing.JLabel();
        jLabel4_Dias = new javax.swing.JLabel();
        jLabel5_Horarios = new javax.swing.JLabel();
        jRadioButton1_Segunda = new javax.swing.JRadioButton();
        jRadioButton2_Terça = new javax.swing.JRadioButton();
        jRadioButton3_Quarta = new javax.swing.JRadioButton();
        jRadioButton4_Quinta = new javax.swing.JRadioButton();
        jRadioButton5_Sexta = new javax.swing.JRadioButton();
        jButton1_Salvar = new javax.swing.JButton();
        jLabel1_ID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1_Alterar = new javax.swing.JButton();
        jTextField1_ID = new javax.swing.JFormattedTextField();
        jTextField1_Ano = new javax.swing.JFormattedTextField();
        jTextField2_Semestre = new javax.swing.JFormattedTextField();
        jTextField3_HorarioComeco1 = new javax.swing.JFormattedTextField();
        jTextField5_HorarioTermino1 = new javax.swing.JFormattedTextField();
        jTextField4_HorarioComeco2 = new javax.swing.JFormattedTextField();
        jTextField6_HorarioTermino2 = new javax.swing.JFormattedTextField();
        jButton2_Sair = new javax.swing.JButton();
        jLabel1_Titulo = new javax.swing.JLabel();
        jLabel1_Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 550));
        setSize(new java.awt.Dimension(701, 550));
        getContentPane().setLayout(null);

        jPanel1_PainelMaior.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2_PainelMenor.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2_PainelMenor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2_PainelMenor.setLayout(null);

        jLabel2_Ano.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2_Ano.setText("Ano:");
        jPanel2_PainelMenor.add(jLabel2_Ano);
        jLabel2_Ano.setBounds(11, 71, 31, 17);

        jLabel3_Semestre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3_Semestre.setText("Semestre: ");
        jPanel2_PainelMenor.add(jLabel3_Semestre);
        jLabel3_Semestre.setBounds(11, 102, 68, 17);

        jLabel4_Dias.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4_Dias.setText("Dias da Semana: ");
        jPanel2_PainelMenor.add(jLabel4_Dias);
        jLabel4_Dias.setBounds(11, 132, 112, 17);

        jLabel5_Horarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5_Horarios.setText("Horários de Realização: ");
        jPanel2_PainelMenor.add(jLabel5_Horarios);
        jLabel5_Horarios.setBounds(11, 212, 154, 17);

        jRadioButton1_Segunda.setText("Segunda-Feira");
        jPanel2_PainelMenor.add(jRadioButton1_Segunda);
        jRadioButton1_Segunda.setBounds(11, 156, 95, 14);

        jRadioButton2_Terça.setText("Terça-Feira");
        jPanel2_PainelMenor.add(jRadioButton2_Terça);
        jRadioButton2_Terça.setBounds(106, 156, 81, 14);

        jRadioButton3_Quarta.setText("Quarta-Feira");
        jPanel2_PainelMenor.add(jRadioButton3_Quarta);
        jRadioButton3_Quarta.setBounds(187, 156, 87, 14);

        jRadioButton4_Quinta.setText("Quinta-Feira");
        jPanel2_PainelMenor.add(jRadioButton4_Quinta);
        jRadioButton4_Quinta.setBounds(11, 176, 85, 14);

        jRadioButton5_Sexta.setText("Sexta-Feira");
        jPanel2_PainelMenor.add(jRadioButton5_Sexta);
        jRadioButton5_Sexta.setBounds(106, 176, 81, 14);

        jButton1_Salvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1_Salvar.setText("Salvar");
        jPanel2_PainelMenor.add(jButton1_Salvar);
        jButton1_Salvar.setBounds(180, 280, 105, 25);

        jLabel1_ID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1_ID.setText("ID: ");
        jPanel2_PainelMenor.add(jLabel1_ID);
        jLabel1_ID.setBounds(187, 13, 21, 17);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Status: ");
        jPanel2_PainelMenor.add(jLabel1);
        jLabel1.setBounds(11, 13, 48, 17);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton1.setText("Ativo");
        jPanel2_PainelMenor.add(jRadioButton1);
        jRadioButton1.setBounds(11, 34, 51, 18);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton2.setText("Inativo");
        jPanel2_PainelMenor.add(jRadioButton2);
        jRadioButton2.setBounds(80, 34, 61, 18);

        jButton1_Alterar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1_Alterar.setText("Alterar");
        jPanel2_PainelMenor.add(jButton1_Alterar);
        jButton1_Alterar.setBounds(19, 280, 88, 25);

        try {
            jTextField1_ID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2_PainelMenor.add(jTextField1_ID);
        jTextField1_ID.setBounds(212, 12, 70, 20);

        try {
            jTextField1_Ano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2_PainelMenor.add(jTextField1_Ano);
        jTextField1_Ano.setBounds(90, 70, 70, 20);

        try {
            jTextField2_Semestre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#º")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2_PainelMenor.add(jTextField2_Semestre);
        jTextField2_Semestre.setBounds(90, 100, 70, 20);

        try {
            jTextField3_HorarioComeco1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2_PainelMenor.add(jTextField3_HorarioComeco1);
        jTextField3_HorarioComeco1.setBounds(170, 210, 50, 20);

        try {
            jTextField5_HorarioTermino1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2_PainelMenor.add(jTextField5_HorarioTermino1);
        jTextField5_HorarioTermino1.setBounds(230, 210, 50, 20);

        try {
            jTextField4_HorarioComeco2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2_PainelMenor.add(jTextField4_HorarioComeco2);
        jTextField4_HorarioComeco2.setBounds(170, 240, 50, 20);

        try {
            jTextField6_HorarioTermino2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2_PainelMenor.add(jTextField6_HorarioTermino2);
        jTextField6_HorarioTermino2.setBounds(230, 240, 50, 20);

        jButton2_Sair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2_Sair.setText("Sair");
        jButton2_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_SairActionPerformed(evt);
            }
        });

        jLabel1_Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1_Titulo.setText("Cadastro de Disciplinas");

        jLabel1_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apresentacao/graduation-hat-and-diploma-2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1_PainelMaiorLayout = new javax.swing.GroupLayout(jPanel1_PainelMaior);
        jPanel1_PainelMaior.setLayout(jPanel1_PainelMaiorLayout);
        jPanel1_PainelMaiorLayout.setHorizontalGroup(
            jPanel1_PainelMaiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_PainelMaiorLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1_PainelMaiorLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel2_PainelMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1_PainelMaiorLayout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(jButton2_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1_PainelMaiorLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1_Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1_PainelMaiorLayout.setVerticalGroup(
            jPanel1_PainelMaiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1_PainelMaiorLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel2_PainelMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jButton2_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1_Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1_PainelMaior);
        jPanel1_PainelMaior.setBounds(0, 0, 690, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_SairActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButton2_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplinaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplinaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplinaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplinaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarDisciplinaSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup1_Dias;
    private javax.swing.JButton jButton1_Alterar;
    private javax.swing.JButton jButton1_Salvar;
    private javax.swing.JButton jButton2_Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Fundo;
    private javax.swing.JLabel jLabel1_ID;
    private javax.swing.JLabel jLabel1_Titulo;
    private javax.swing.JLabel jLabel2_Ano;
    private javax.swing.JLabel jLabel3_Semestre;
    private javax.swing.JLabel jLabel4_Dias;
    private javax.swing.JLabel jLabel5_Horarios;
    private javax.swing.JPanel jPanel1_PainelMaior;
    private javax.swing.JPanel jPanel2_PainelMenor;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton1_Segunda;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton2_Terça;
    private javax.swing.JRadioButton jRadioButton3_Quarta;
    private javax.swing.JRadioButton jRadioButton4_Quinta;
    private javax.swing.JRadioButton jRadioButton5_Sexta;
    private javax.swing.JFormattedTextField jTextField1_Ano;
    private javax.swing.JFormattedTextField jTextField1_ID;
    private javax.swing.JFormattedTextField jTextField2_Semestre;
    private javax.swing.JFormattedTextField jTextField3_HorarioComeco1;
    private javax.swing.JFormattedTextField jTextField4_HorarioComeco2;
    private javax.swing.JFormattedTextField jTextField5_HorarioTermino1;
    private javax.swing.JFormattedTextField jTextField6_HorarioTermino2;
    // End of variables declaration//GEN-END:variables
}
