/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import main.Main;

/**
 *
 * @author kevin.guimaraes
 */
public class TelaLogin extends javax.swing.JFrame {

    
     Main oMain = new Main();
     
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1_Sair = new javax.swing.JButton();
        jButton1_Secretaria = new javax.swing.JButton();
        jButton2_RH = new javax.swing.JButton();
        jButton3_Professor = new javax.swing.JButton();
        jButton4_Aluno = new javax.swing.JButton();
        jButton5_Coordenador = new javax.swing.JButton();
        jLabel1_Fundo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(701, 550));
        getContentPane().setLayout(null);

        jButton1_Sair.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1_Sair.setText("Sair");
        jButton1_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SairActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_Sair);
        jButton1_Sair.setBounds(560, 510, 105, 23);

        jButton1_Secretaria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1_Secretaria.setText("Secretária");
        jButton1_Secretaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1_Secretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SecretariaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_Secretaria);
        jButton1_Secretaria.setBounds(130, 30, 145, 84);

        jButton2_RH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2_RH.setText("RH");
        jButton2_RH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jButton2_RH);
        jButton2_RH.setBounds(380, 30, 145, 84);

        jButton3_Professor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3_Professor.setText("Professor");
        jButton3_Professor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jButton3_Professor);
        jButton3_Professor.setBounds(380, 190, 145, 84);

        jButton4_Aluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4_Aluno.setText("Aluno");
        jButton4_Aluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jButton4_Aluno);
        jButton4_Aluno.setBounds(130, 190, 145, 84);

        jButton5_Coordenador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton5_Coordenador.setText("Coordenador");
        jButton5_Coordenador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5_Coordenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_CoordenadorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5_Coordenador);
        jButton5_Coordenador.setBounds(260, 320, 145, 84);

        jLabel1_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apresentacao/graduation-hat-and-diploma-2.png"))); // NOI18N
        getContentPane().add(jLabel1_Fundo);
        jLabel1_Fundo.setBounds(40, 0, 620, 550);
    }// </editor-fold>//GEN-END:initComponents

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }
    private void jButton5_CoordenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_CoordenadorActionPerformed
        // TODO add your handling code here:
        TelaCoordenador Tcad = new TelaCoordenador(oMain);
        Tcad.show();
    }//GEN-LAST:event_jButton5_CoordenadorActionPerformed

    private void jButton1_SecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SecretariaActionPerformed
        // TODO add your handling code here:
        TelaPrincipalEscolhaSecretaria Tcad = new TelaPrincipalEscolhaSecretaria(oMain);
        Tcad.show();
        
    }//GEN-LAST:event_jButton1_SecretariaActionPerformed

    private void jButton1_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SairActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1_SairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Sair;
    private javax.swing.JButton jButton1_Secretaria;
    private javax.swing.JButton jButton2_RH;
    private javax.swing.JButton jButton3_Professor;
    private javax.swing.JButton jButton4_Aluno;
    private javax.swing.JButton jButton5_Coordenador;
    private javax.swing.JLabel jLabel1_Fundo;
    // End of variables declaration//GEN-END:variables
}
