/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import main.Main;

/**
 *
 * @author Roberto
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    Main oMain ;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
         oMain = new Main();
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1_Secretaria = new javax.swing.JButton();
        jButton2_RH = new javax.swing.JButton();
        jButton4_Aluno = new javax.swing.JButton();
        jButton3_Professor = new javax.swing.JButton();
        jButton5_Coordenador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1_Secretaria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1_Secretaria.setText("Secretária");
        jButton1_Secretaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1_Secretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SecretariaActionPerformed(evt);
            }
        });

        jButton2_RH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2_RH.setText("RH");
        jButton2_RH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2_RH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_RHActionPerformed(evt);
            }
        });

        jButton4_Aluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4_Aluno.setText("Aluno");
        jButton4_Aluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_AlunoActionPerformed(evt);
            }
        });

        jButton3_Professor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3_Professor.setText("Professor");
        jButton3_Professor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_ProfessorActionPerformed(evt);
            }
        });

        jButton5_Coordenador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton5_Coordenador.setText("Coordenador");
        jButton5_Coordenador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5_Coordenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_CoordenadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1_Secretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButton5_Coordenador, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Secretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton5_Coordenador, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_SecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SecretariaActionPerformed
        // TODO add your handling code here:
        TelaPrincipalEscolhaSecretaria Tcad = new TelaPrincipalEscolhaSecretaria(oMain);
        Tcad.show();

    }//GEN-LAST:event_jButton1_SecretariaActionPerformed

    private void jButton5_CoordenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_CoordenadorActionPerformed
        // TODO add your handling code here:
        TelaCoordenador Tcad = new TelaCoordenador(oMain);
        Tcad.show();
    }//GEN-LAST:event_jButton5_CoordenadorActionPerformed

    private void jButton2_RHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_RHActionPerformed
        // TODO add your handling code here:
        
        TelaRH Tcad = new TelaRH(oMain);
        Tcad.show();
    }//GEN-LAST:event_jButton2_RHActionPerformed

    private void jButton4_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_AlunoActionPerformed
        // TODO add your handling code here:
        ConsultarAvaliaçãoAluno Tcad = new ConsultarAvaliaçãoAluno(oMain);
        Tcad.show();
        
    }//GEN-LAST:event_jButton4_AlunoActionPerformed

    private void jButton3_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_ProfessorActionPerformed
        // TODO add your handling code here:]
        TelaProfessor Tcad = new TelaProfessor(oMain);
        Tcad.show();
    }//GEN-LAST:event_jButton3_ProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Secretaria;
    private javax.swing.JButton jButton2_RH;
    private javax.swing.JButton jButton3_Professor;
    private javax.swing.JButton jButton4_Aluno;
    private javax.swing.JButton jButton5_Coordenador;
    // End of variables declaration//GEN-END:variables
}
