/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import main.Main;

/**
 *
 * @author Kevin
 */
public class TelaProfessor extends javax.swing.JFrame {
    
       private Main  oMain ; 
    
    /**
     * Creates new form TelaCadastrarCursoSecretaria
     */
    public TelaProfessor(Main oMain) {
        initComponents();
        this.oMain = oMain; 
    }

    /**
     * Creates new form TelaProfessor
     */
    public TelaProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2_Titulo = new javax.swing.JLabel();
        jPanel2_PainelMenor = new javax.swing.JPanel();
        jComboBox1_Alunos = new javax.swing.JComboBox<>();
        jLabel1_Aluno = new javax.swing.JLabel();
        jLabel1_Nota1 = new javax.swing.JLabel();
        jLabel2_Nota2 = new javax.swing.JLabel();
        jLabel3_NotaProvaFinal = new javax.swing.JLabel();
        jLabel4_Frequencia = new javax.swing.JLabel();
        jButton1_Salvar = new javax.swing.JButton();
        jTextField1_Nota1 = new javax.swing.JTextField();
        jTextField2_Nota2 = new javax.swing.JTextField();
        jTextField3_NotaProvaFinal = new javax.swing.JTextField();
        jTextField4_Frequencia = new javax.swing.JTextField();
        jButton1_Alterar = new javax.swing.JButton();
        jButton1_Sair = new javax.swing.JButton();
        jLabel1_Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(701, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2_Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2_Titulo.setText("Lançamento de Avaliações");
        jPanel1.add(jLabel2_Titulo);
        jLabel2_Titulo.setBounds(180, 0, 350, 30);

        jPanel2_PainelMenor.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2_PainelMenor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2_PainelMenor.setLayout(null);

        jComboBox1_Alunos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1_Alunos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2_PainelMenor.add(jComboBox1_Alunos);
        jComboBox1_Alunos.setBounds(60, 40, 290, 21);

        jLabel1_Aluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1_Aluno.setText("Aluno:");
        jPanel2_PainelMenor.add(jLabel1_Aluno);
        jLabel1_Aluno.setBounds(10, 40, 50, 14);

        jLabel1_Nota1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1_Nota1.setText("Nota 1:");
        jPanel2_PainelMenor.add(jLabel1_Nota1);
        jLabel1_Nota1.setBounds(20, 90, 50, 15);

        jLabel2_Nota2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2_Nota2.setText("Nota 2:");
        jPanel2_PainelMenor.add(jLabel2_Nota2);
        jLabel2_Nota2.setBounds(20, 120, 40, 15);

        jLabel3_NotaProvaFinal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3_NotaProvaFinal.setText("Nota Prova Final:");
        jPanel2_PainelMenor.add(jLabel3_NotaProvaFinal);
        jLabel3_NotaProvaFinal.setBounds(20, 150, 110, 15);

        jLabel4_Frequencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4_Frequencia.setText("Frequencia:");
        jPanel2_PainelMenor.add(jLabel4_Frequencia);
        jLabel4_Frequencia.setBounds(20, 180, 70, 15);

        jButton1_Salvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1_Salvar.setText("Salvar");
        jButton1_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SalvarActionPerformed(evt);
            }
        });
        jPanel2_PainelMenor.add(jButton1_Salvar);
        jButton1_Salvar.setBounds(227, 225, 110, 30);
        jPanel2_PainelMenor.add(jTextField1_Nota1);
        jTextField1_Nota1.setBounds(150, 90, 59, 20);
        jPanel2_PainelMenor.add(jTextField2_Nota2);
        jTextField2_Nota2.setBounds(150, 120, 59, 20);
        jPanel2_PainelMenor.add(jTextField3_NotaProvaFinal);
        jTextField3_NotaProvaFinal.setBounds(150, 150, 59, 20);
        jPanel2_PainelMenor.add(jTextField4_Frequencia);
        jTextField4_Frequencia.setBounds(150, 180, 59, 20);

        jButton1_Alterar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1_Alterar.setText("Alterar");
        jPanel2_PainelMenor.add(jButton1_Alterar);
        jButton1_Alterar.setBounds(30, 225, 101, 30);

        jPanel1.add(jPanel2_PainelMenor);
        jPanel2_PainelMenor.setBounds(170, 70, 360, 300);

        jButton1_Sair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1_Sair.setText("Sair");
        jButton1_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SairActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_Sair);
        jButton1_Sair.setBounds(530, 480, 100, 23);

        jLabel1_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apresentacao/graduation-hat-and-diploma-2.png"))); // NOI18N
        jPanel1.add(jLabel1_Fundo);
        jLabel1_Fundo.setBounds(110, 0, 620, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1_SairActionPerformed

    private void jButton1_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_SalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Alterar;
    private javax.swing.JButton jButton1_Sair;
    private javax.swing.JButton jButton1_Salvar;
    private javax.swing.JComboBox<String> jComboBox1_Alunos;
    private javax.swing.JLabel jLabel1_Aluno;
    private javax.swing.JLabel jLabel1_Fundo;
    private javax.swing.JLabel jLabel1_Nota1;
    private javax.swing.JLabel jLabel2_Nota2;
    private javax.swing.JLabel jLabel2_Titulo;
    private javax.swing.JLabel jLabel3_NotaProvaFinal;
    private javax.swing.JLabel jLabel4_Frequencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2_PainelMenor;
    private javax.swing.JTextField jTextField1_Nota1;
    private javax.swing.JTextField jTextField2_Nota2;
    private javax.swing.JTextField jTextField3_NotaProvaFinal;
    private javax.swing.JTextField jTextField4_Frequencia;
    // End of variables declaration//GEN-END:variables
}
